### ISSUE TITLE
Standardize datetime handling

### ISSUE THREAD

**Issue by julian-george** [ospreyelm/HarmonyLab#106]
Currently, some datetimes are handled by the builtin `datetime` module, others are handled by the external `pytz` module, and all of them kind of differ slightly, and there are a variety of methods and functions that deal with datetimes, many being legacy code. Ideally, there should be a method on the playlist/course model which is a single source of truth for all due dates and publish dates.

**Comment by ospreyelm** [comment]
Dates functions now simplified, improved, and better commented; unless these functions break or slow performance, no need to change them at the moment. However, we do need to add a timezone property to courses in order for course authors to determine the timezone in which their publish and due dates will be interpreted, in addition to properties for the times of day at which their publish and due dates will be interpreted.

**Comment by ospreyelm** [comment]
Dates functions now simplified, improved, and better commented; unless these functions break or slow performance, no need to change them at the moment.
