### ISSUE TITLE
performance_dict data validity

### ISSUE THREAD

**Issue by julian-george** [ospreyelm/HarmonyLab#108]
- [ ] Fix display of performances in instructor CourseActivityView, lots of erroneous readings
- [ ] Figure out better enforcement/updating of performance_dict in cases such as playlist reordering, deletion, user data switching, subscribed group editing, etc... This will probably involve Django interceptors or similar query side effects

**Comment by ospreyelm** [comment]
Fix should be within easy reach now. We must use playlist IDs instead of order as the performance dictionary keys for a course.
