### ISSUE TITLE
Fix exercise locking

### ISSUE THREAD

**Issue by julian-george** [ospreyelm/HarmonyLab#109]
Currently, exercises that have already been performed in a transposition are not being marked as locked. This presumably has something to do with the changes to transposition in the models. Figure out why performing a transposed exercise doesn't lock the exercise, fix it, and write a migration to search through PerformanceData for exercises that are erroneously unlocked and lock them.

**Comment by ospreyelm** [comment]
Cause of this is now resolved. Migrations still needed.
